### ISSUE TITLE
Enable custom unit prefix on axis labels

### ISSUE THREAD

**Issue by vizzu-streamlit** [vizzuhq/vizzu-lib#154]
v1.: Enable other standard options than SI, (K, M, B, T)
v2.: Enable custom options set by the user

Question: Can the same prefixes be used on tooltips and labels? Instead of writing 3458387205, 3.46B or 3,458M could be used.

**Comment by simzer** [comment]
Implemented: https://github.com/vizzuhq/vizzu-lib/pull/155
