### ISSUE TITLE
Example data object in README fails TypeScript validation

### ISSUE THREAD

**Issue by korompaiistvan** [vizzuhq/vizzu-lib#21]
The `data` object in the [Usage section of the README](https://github.com/vizzuhq/vizzu-lib#usage) does not fit the type definition of a `Data.Set`.
See error below (ignore the React specific code around it)
![image](https://user-images.githubusercontent.com/36007115/137594002-c4ae9acf-3407-400f-8678-7ccfa6fa47af.png)

Based on the comment in the type definition file, the `type` property should be made optional on [this line](https://github.com/vizzuhq/vizzu-lib/blob/0be08d90e4d4eb5263513b9c379066aa9b9566be/src/apps/weblib/js-api/vizzu.d.ts#L19)

I also see why it would be strictly required, but then the README needs to be updated to reflect that.

**Comment by simzer** [comment]
Thanks, I made it optional. 690a55b
