### ISSUE TITLE
Problems with loading the Web Assembly module when using code bundlers (Vite, Webpack)

### ISSUE THREAD

**Issue by korompaiistvan** [vizzuhq/vizzu-lib#22]
I'm playing around in a react project created with create-react-app (which uses webpack for bundling) and between how Vizzu is trying to locate its WASM and how webpack bundles it, I can't figure out an elegant way to get it to work.

I realize this is not an issue with Vizzu per se, but wanted to highlight it, as it will be important for the adoption.

Details as I understand them right now.
The vizzu js module tries to import its own wasm module based on its own import path.
![image](https://user-images.githubusercontent.com/36007115/137594819-d558ff5c-4288-420f-979b-76e6bdee5fd2.png)

In my case this resolves to http://localhost:3000/node_modules/vizzu/dist/cvizzu.wasm
![image](https://user-images.githubusercontent.com/36007115/137594716-4ae28253-26ef-4af7-b627-cb085d3783ac.png)

This file path is not recognized by the local dev server (as it only bundles .js/.ts files by default)
Since the path is not recognized it serves the main webpage I'm trying to develop to test the module.
![image](https://user-images.githubusercontent.com/36007115/137594843-c3373928-63f9-4841-91df-e56eef60404e.png)

The wasm parser naturally fails to parse this and I get an empty page.
![image](https://user-images.githubusercontent.com/36007115/137594867-6cb2f680-1e5e-48e3-98f8-205cfa6833fd.png)

I know that there is a way to update the webpack config in order to serve the wasm file on this exact path, which is a half-decent solution but I don't (yet) know how to do it. I'll add details here once I have them

**Comment by korompaiistvan** [comment]
yea for now, that's the best course of action. I'm 100% that we'll figure this out so future users won't have a problem

**Comment by simzer** [comment]
Never mind, I have put in the link (got the description from the repo).

**Comment by korompaiistvan** [comment]
I just found this [repo](https://github.com/viroulep/emscripten-webpack-cra), between that and Christopher's solution, I'll come up with something fairly easy to set up. the more I read about this the more I think it can be solved on the Emscripten side

**Comment by simzer** [comment]
But I'm afraid the emscripten wrapper is still not readable in this version:
https://vizzu-lib-main.storage.googleapis.com/lib/cvizzu.js

If you need a debug build (emscripten generates non-minified code for debug build), then I can produce that for you.

**Comment by simzer** [comment]
If you would like to experiment with the emscripten configuration, and build the project, then
https://github.com/vizzuhq/vizzu-lib/blob/main/project/build.md 
This is the way! :)

**Comment by simzer** [comment]
@korompaiistvan
Thank you for providing the example and the tutorial on how to use Vizzu with React!
https://vizzuhq.github.io/vizzu-react-example/
https://github.com/vizzuhq/vizzu-react-example

**Comment by simzer** [comment]
@korompaiistvan 
I have made the url of the wasm file configurable in Vizzu constructor:
```javascript
let chart = new Vizzu(container, {}, { wasmUrl: 'whatever-folder/cvizzu.wasm' });
```
How much would this help with this bundler issue?

**Comment by simzer** [comment]
I have managed to reduce the problem. Now integrating Vizzu with Webpack needs only the steps listed here:
https://github.com/simzer/vizzu-webpack-demo/blob/main/README.md#adding-vizzu-to-a-project-which-using-webpack

**Comment by korompaiistvan** [comment]
i think that solution in the readme is a decent compromise. not as elegant as it would be if it worked automatically, but basically the next best thing

**Comment by simzer** [comment]
@korompaiistvan 
Thanks, we will put this into our tutorial with some explanation then. 
I will also try to update https://github.com/vizzuhq/vizzu-react-example and send a PR for you if you'd be willing to do a review.

**Comment by simzer** [comment]
I was unable to update the react example. 
If I use the solution from the webpack-demo, it won't work with `npm start`.
However, I was able to build a correctly working version with `npm run build`.

**Comment by korompaiistvan** [comment]
that's probably got to do something with how CRA deals with webpack config (badly).
did you modify the config overrides js file or create a separate webpack config file?

also as a note: webpack devserver (npm start) and build works slightly differently so there might be a difference there as well.

I'm also wondering about postprocessing your npm package instead so it includes this explicit import but im not sure how exactly

**Comment by simzer** [comment]
I have modified the config-override.js file.

**Comment by simzer** [comment]
I have tried devserver (`webpack serve`) in the webpack-demo repo, and it works there.

**Comment by simzer** [comment]
PR sent to https://github.com/vizzuhq/vizzu-react-example. Closing this issue.
