### ISSUE TITLE
Types for colorPalette seem wrong

### ISSUE THREAD

**Issue by christopher-caldwell** [vizzuhq/vizzu-lib#28]
The types for color palettes are a little odd.

```ts
type Color = `#${number}`
	|`rgb(${number},${number},${number})`
	|`rgba(${number},${number},${number},${number})`;

type ColorPalette = Color 
	| `${Color} ${Color}` 
	| `${Color} ${Color} ${Color}`
	| `${Color} ${Color} ${Color} ${Color}`
	| `${Color} ${Color} ${Color} ${Color} ${Color}`;
```

This makes sense, but in the docs, and in many CSS hex codes, they aren't just numbers.

In the [docs](https://lib.vizzuhq.com/0.3.0/#chapter-0.12#snippet-0.12.1), the examples give `#9355e8FF #123456FF #BDAF10FF` as a valid option, but this throws a TS error because there are numbers and letters.

Changing the color template string to `#1 #11 #1` fixes the TS error, but is not actually valid.

## Possible Solution

```
type Color = `#${number | string}`
	|`rgb(${number},${number},${number})`
	|`rgba(${number},${number},${number},${number})`;
```

This solves my use case, but I'm not sure if there was some logic around needing to be a number?

**Comment by simzer** [comment]
The ColorPalette definition is also wrong, it can handle more than 5 colors, but I couldn't find a way to define it to arbitrary length in TS.
