### ISSUE TITLE
No Layout/font recalc on resize, only when animate called

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/vizzu-lib#315]
Default style parameters recalculated only when animate called, causing strange effect after canvas resize, that the chart fonts, paddings adjust only when the next animation called.

Peter:
Chart elements don't scale proportionally when the full-screen mode is turned on (also won't shrink when it's turned off) 
https://github.com/vizzuhq/ipyvizzu-story/assets/10341970/fcc5dfae-d577-4f53-837a-53a24f7f45a3

**Comment by simzer** [comment]
Workaround: set root fontSize to 100%
