### ISSUE TITLE
Numbers on label run to zero on removal

### ISSUE THREAD

**Issue by korompaiistvan** [vizzuhq/vizzu-lib#32]
Upon removing a series from label, the numbers run to zero while fading out.
See below gif
![labelrundown](https://user-images.githubusercontent.com/36007115/138524290-e8ddb76c-d816-4cf4-a94b-6b7322f9af84.gif)

Is this intended? My expectation would be a simple fadeout.

**Comment by simzer** [comment]
Fixed in 0.4.0
