### ISSUE TITLE
Example code in logo animation

### ISSUE THREAD

**Issue by CrashLaker** [vizzuhq/vizzu-lib#33]
Hi all!

Awesome project!
I'm looking for the example code which made the logo gif.
Is it shareable?

Atm i'm trying to concat the animations from 1 -> 2 in examples wihout success

https://lib.vizzuhq.com/0.3.0/#example-1.1.0
![image](https://user-images.githubusercontent.com/4432491/138531304-22b28563-ed85-44ff-8796-29451a46de1a.png)

https://lib.vizzuhq.com/0.3.0/#example-1.1.1
![image](https://user-images.githubusercontent.com/4432491/138531372-3b03efc3-e3e6-40af-9e71-588aa58be166.png)

can anyone guide/help me?
https://jsfiddle.net/crashlaker/7L3yg1bk/

regards,
C.

ps: perhaps we could only do this with the same dataset

**Comment by petervidos** [comment]
Hi,
Thanks :)

We haven't made the full code for the logo animation available yet, but we'll do that soon, and I'll let you know when it's done.

Regarding connecting these two animations: yes, they both have to use the same dataset for that.
Most of the animated tests are built on the same dataset, except for the one from the logo, so maybe, for now, it's easier if you try to connect two other samples.

If you want to join the conversation with the others who have started using the lib, you might want to come to our Slack workspace: https://join.slack.com/t/vizzu-community/shared_invite/zt-w2nqhq44-2CCWL4o7qn2Ns1EFSf9kEg.
It would be great to have you there!
