### ISSUE TITLE
Filtering error in waterfall charts

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/vizzu-lib#470]
When creating a waterfall chart (same dimension on both axes, measure on one axis), and filtering some of the categories at the same time, the space for the filtered categories is shown on the axis with only the category (x-axis in the attached example). 
To put it simple: The empty space on the left shouldn't be there :)

![image](https://github.com/vizzuhq/vizzu-lib/assets/10341970/e6a9d043-d6b4-4d9a-a509-4892c8d7f088)
[waterfall_error.zip](https://github.com/vizzuhq/vizzu-lib/files/13921705/waterfall_error.zip)

**Comment by schaumb** [comment]
simplified dataset: https://jsfiddle.net/3s154uyd/4/

**Comment by schaumb** [comment]
Surprisingly this issue has the same root cause as [another bug](https://github.com/vizzuhq/vizzu-lib/issues/250#issuecomment-1767892787). (The data contains independent dimension values.)

**Comment by schaumb** [comment]
This issue solved in [v0.11.1](https://github.com/vizzuhq/vizzu-lib/releases/tag/v0.11.1): `When the first marker was disabled it was calculated as an enabled marker on the XY normalization.` See [here](https://jsfiddle.net/ep7hnfdq/12/)
