### ISSUE TITLE
Integrate with Hal9

### ISSUE THREAD

**Issue by javierluraschi** [vizzuhq/vizzu-lib#48]
Would anyone be interested in providing chart blocks for [hal9.com](https://hal9.com)? You can send us PRs to [https://github.com/hal9ai/hal9ai](https://github.com/hal9ai/hal9ai)

**Comment by mathieujobin** [comment]
?!?

**Comment by simzer** [comment]
I left this open for a while in case anybody is interested, but this is not really a task for this project.
