### ISSUE TITLE
How do we skip displaying values on the X axis?

### ISSUE THREAD

**Issue by mathieujobin** [vizzuhq/vizzu-lib#63]
Hi,

my X axis contains more than 700 values (dates), which overlaps and looks like a big gray box.

![image](https://user-images.githubusercontent.com/99191/148541541-dceac56d-396a-4749-b273-09db67d5eb5b.png)

How do I skip values, or override how this is displayed?

thanks

**Comment by simzer** [comment]
Hi,
This behavior cannot be configured explicitly for now. However, you can override the label drawing event to solve this.
Here is an example, which does the same:
https://github.com/vizzuhq/vizzu-lib-doc/blob/main/docs/stories/musicformats/musicformats.js#L87
(the event handler in this example will allow the rendering of every 5th label) 

You may also want to rotate the labels if they still overlap by setting the plot.xAxis.label.angle style parameter.

**Comment by mathieujobin** [comment]
Oh thank you ! That's a very helpful work around.

its my first time with Vizzu, it works amazingly great, even if tons of data.

**Comment by simzer** [comment]
Thanks, I'm glad that you're happy with Vizzu!
I will leave this issue open as a feature request. We shall add a config parameter for this behavior in the future.

**Comment by simzer** [comment]
@mathieujobin One more thing: It would be great to see what you build using Vizzu. Send us a link if you feel like it.

**Comment by mathieujobin** [comment]
Sure thing
https://fifty-fifty.5gl.org/covid/tokyo_cases_per_city

I've been waiting for a library like Vizzu for a long time, D3 has never worked well for me.
Backend is Rails 7, and it was super easy to integrate it.

**Comment by simzer** [comment]
Thanks!

**Comment by mathieujobin** [comment]
I don't mind the existing workaround, works well.

closing this
