### ISSUE TITLE
Uncaught TypeError: this.tooltip is undefined

### ISSUE THREAD

**Issue by jchrom** [vizzuhq/vizzu-lib#69]
Perhaps I am doing something silly, but trying to recreate [the tutorial](https://lib.vizzuhq.com/0.4/#chapter-0.2) line by line, I get this error when trying to add a tooltip.

<details>
  <summary>code</summary>

```
import Vizzu from "https://cdn.jsdelivr.net/npm/vizzu@0.4.3/dist/vizzu.min.js";

let data = {
  series: [
  {
    name: 'Genres',
    type: 'dimension',
    values: [
    'Pop', 'Rock', 'Jazz', 'Metal',
    'Pop', 'Rock', 'Jazz', 'Metal',
    'Pop', 'Rock', 'Jazz', 'Metal'
    ]
  },
  {
    name: 'Types',
    type: 'dimension',
    values: [
    'Hard', 'Hard', 'Hard', 'Hard',
    'Smooth', 'Smooth', 'Smooth', 'Smooth',
    'Experimental', 'Experimental', 'Experimental', 'Experimental'
    ]
  },
  {
    name: 'Popularity',
    type: 'measure',
    values: [ 114, 96, 78, 52, 56, 36, 174, 121, 127, 83, 94, 58 ]
  }
  ]
};

let chart = new Vizzu('vizzu-tooltip')

chart.animate({ data });

chart.animate({
  config: {
    channels: {
      x: { set: ['Genres'] },
      y: { set: ['Popularity'] }
    }
  }
})

chart.feature('tooltip',true)
```
</details>

I am on vizzu@0.4.3, using npm live-server.

**Comment by simzer** [comment]
Hi!
When you call the constructor of Vizzu, it will initialize the library in an async manner. You can call feature() method only when the initialization is finished. To do this, you can use the initializing promise to chain your code after. 
```javascript
chart.initializing.then(chart => {
	chart.feature('tooltip',true);
	return chart;
})
```
Working example of your snippet:
https://jsfiddle.net/VizzuHQ/dk7b86vc/84/

I'm curious what dataviz you plan to build. That would be great if you could share it when it's ready!

**Comment by jchrom** [comment]
: face_palm :

Thank you Laszlo! I am still finding my way around it, but will be glad to share when ready. This can be closed.
