### ISSUE TITLE
Update the Readme so it works with React and other frameworks

### ISSUE THREAD

**Issue by chideraike** [vizzuhq/vizzu-lib#71]

**Comment by simzer** [comment]
Hi, it's not clear to me what changes would you like to see in the readme.
Do you mean we should add descriptions on how to use the library with React?

**Comment by nguaman** [comment]
> Hi, it's not clear to me what changes would you like to see in the readme. Do you mean we should add descriptions on how to use the library with React?

Could be nice to have an example of how vizzu works with react.

**Comment by simzer** [comment]
I see. Thanks, good idea. We will create a tutorial on that topic. Meanwhile, you can check out how these repos made Vizzu work in react: 
https://github.com/christopher-caldwell/vizzu-vite-demo
https://github.com/korompaiistvan/vizzu-react

**Comment by simzer** [comment]
@korompaiistvan created an example and a tutorial on how to set up Vizzu with React:
howto: https://vizzuhq.github.io/vizzu-react-example/
example: https://github.com/vizzuhq/vizzu-react-example

These links are added to the FAQ and the external projects list, both accessible from the readme as well.
